FROM python:3.13-alpine

WORKDIR /app

RUN mkdir -p /app/certs

# Copy the entire modular structure
COPY ./core/ /app/core/
COPY ./api/ /app/api/
COPY ./api/requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run uvicorn with SSL certificates
CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "/app/certs/server.key", "--ssl-certfile", "/app/certs/server.crt"]