FROM python:3.13-alpine

WORKDIR /app

RUN mkdir -p /app/certs

# Copy the entire modular structure
COPY ./core/ /app/core/
COPY ./api/ /app/api/
COPY ./api/requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Use environment variables from .env file for SSL paths
CMD uvicorn api.app:app --host 0.0.0.0 --port 443 --ssl-keyfile ${SSL_KEY_PATH} --ssl-certfile ${SSL_CERT_PATH}
