FROM python:3.13-alpine

WORKDIR /app

RUN mkdir -p /app/certs

COPY ./api/app.py /app/
COPY ./api/requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# Run uvicorn with SSL certificates
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "443", "--ssl-keyfile", "/app/certs/server.key", "--ssl-certfile", "/app/certs/server.crt"]