FROM python:3.13-alpine

WORKDIR /app

RUN mkdir -p /app/certs

COPY ./bridge/mqtt_bridge.py /app/
COPY ./bridge/requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "mqtt_bridge.py"]