FROM python:3.13-alpine

WORKDIR /app

RUN mkdir -p /app/certs

# Copy the entire modular structure
COPY ./core/ /app/core/
COPY ./bridge/ /app/bridge/
COPY ./bridge/requirements.txt /app/

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the bridge script
CMD ["python", "-m", "bridge.mqtt_bridge"]
