services:
    # backend:
    #     depends_on:
    #         - db
    db:
        image: timescale/timescaledb-ha:pg17
        restart: always
        ports:
            - 5432:5432
        volumes:
            - itp_db:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgrespassword
volumes:
    itp_db: